name: ServerInformation
version: 1.0
main: com.altoya.information.Main

commands:
  discordlink:
    description: Sends the player the discord link
    usage: /discordlink
  serverip:
    description: Sends the player the server ip
    usage: /ip
  staff:
    description: Sends the player a list of staff
    usage: /staff
  rules:
    description: Sends the player a list of the rules
    usage: /rules
  store:
    description: Sends the player the store link
    usage: /store